{% set name = "pydot" %}
{% set version = "3.0.1" %}
{% set sha256 = "e18cf7f287c497d77b536a3d20a46284568fea390776dface6eabbdf1b1b5efc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - python
    - pyparsing >=3
  run:
    - python
    - pyparsing >=3
    - graphviz >=2.38.0

test:
  imports:
    - pydot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erocarrera/pydot
  license: MIT
  license_file: LICENSES/MIT.txt
  summary: Python interface to Graphviz's Dot
  description: |
    This module provides with a full interface to create handle modify and
    process graphs in Graphviz’s dot language.
  doc_url: https://pypi.python.org/pypi/pydot
  dev_url: https://github.com/erocarrera/pydot

extra:
  recipe-maintainers:
    - nehaljwani
    - leycec
