{% set name = "pydot" %}
{% set version = "4.0.0" %}
{% set sha256 = "12f16493337cade2f7631b87c8ccd299ba2e251f3ee5d0732a058df2887afe97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - python
    - pyparsing >=3.0.9
  run:
    - python
    - pyparsing >=3.0.9
    - graphviz >=2.38.0

test:
  imports:
    - pydot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erocarrera/pydot
  license: MIT
  license_file: LICENSES/MIT.txt
  summary: Python interface to Graphviz's Dot
  description: |
    This module provides with a full interface to create handle modify and
    process graphs in Graphviz’s dot language.
  doc_url: https://pypi.python.org/pypi/pydot
  dev_url: https://github.com/erocarrera/pydot

extra:
  recipe-maintainers:
    - nehaljwani
    - leycec
