appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: c9JGfqNdRXZHawW+4Whvdgh1Wxsst1nz8kJwxizYLnjoMG0xTusn4CbAEle3tdO3/UIOdhoaxyy7z2mrRra/55TVqY1Ut8QD4zaoTO86Y7Hu+scRcRvMIRfcsae+o6xHPbq50XCdukx/VTCAcWeyHWRMKaNYihpR6vmReMUXJXkeUYNIQfd8Mq4tcIAqP1Mmr9GQZQgcFbjVO4XdXn6C1RA7f5/JykmlIaR2Ni/8UVMUMhyWIgwCWVDwyKPAxPl7lVZu+0gohyYJKCVqxQpyQq0NCJ9OAihxlbzmw7GJHwWi+odqlPg0xhnKkar4wh4jlWPrSwZgxXhwnfRntGkoeghi2OTXLsjVcQ9fJUPcAdw9WtbvQX/mHTpePhOGQQXBh+4Evgc7kVES94gS3dEAthydR2dLbOny5zK4Z6tr6kkYbktfUL/ms1Z+gi8rgB7wOD9U1cPWJbNx897AdYoDBs+xFMhQAXeE/CNNm4MrdWcZ6mV/7GyrAkCQC8WEkvAejdYhGwHbqAdJpIYlsIFC8rwHCY0EpPB11lf2FcR21MbJGvT9zi9KNOyo/69dXbs70kwhYwdyKn22fDoWD7cIrsttavxkq4hSTKHYdmmOEQFQkmRIGoNTLo/3tXWo+HOvdRBQAvGudNP3RBjqS43oR1O0IP1C5hh/kIHZKNN3fY0=}
provider:
  win: azure
conda_forge_output_validation: true
